
name: PKPL CI/CD Pipeline

# Pemicu (trigger) kapan workflow ini akan dijalankan
on:
  # Dijalankan setiap kali ada 'push' ke branch 'main'
  push:
    branches: [ "main" ]

# Daftar semua pekerjaan (jobs) yang akan dijalankan dalam pipeline
jobs:
  # --- JOB 1: MENJALANKAN UNIT TESTS ---
  test:
    name: Run Unit Tests
    # Menjalankan job ini di server virtual Ubuntu terbaru
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Mengunduh (checkout) kode dari repository Anda ke server
      - name: Check out code
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan lingkungan Node.js versi 18
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Langkah 3: Menginstall semua dependency yang ada di package.json
      - name: Install dependencies
        run: npm install

      # Langkah 4: Memberikan izin eksekusi pada Jest (perbaikan spesifik)
      - name: Add execute permission to jest
        run: chmod +x ./node_modules/.bin/jest

      # Langkah 5: Menjalankan skrip 'test' dari package.json
      - name: Run tests
        run: npm test

  # --- JOB 2: BUILD & PUSH DOCKER IMAGE ---
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    # Job ini baru akan berjalan JIKA job 'test' selesai dengan sukses
    needs: test
    steps:
      # Langkah 1: Mengunduh kode dari repository Anda
      - name: Check out code
        uses: actions/checkout@v4

      # Langkah 2: Login ke Docker Hub secara aman menggunakan secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Langkah 3: Build image dari Dockerfile dan push ke Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # Konteks build adalah direktori root (tempat Dockerfile berada)
          context: .
          # Mengaktifkan proses push setelah build berhasil
          push: true
          # Memberi tag pada image (praktik terbaik dengan multi-tagging)
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/uas-pkpl:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/uas-pkpl:${{ github.sha }}
